#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Checking commit message format..."

commit_msg_file=$1
commit_msg=$(cat "$commit_msg_file")

pattern='\[SCRUM-[0-9]+\] .+'


if ! echo "$commit_msg" | grep -Eq "$pattern"; then
  echo ""
  echo "❌ Wrong format: commit message must include [SCRUM-<number>]."
  echo ""
  echo "✅ Correct format example:"
  echo "   [SCRUM-123] your commit message"
  echo ""
  exit 1
fi

echo "✅ Commit message format is valid."
